// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/themes": {
            "get": {
                "description": "Получение списка тем с опциональной пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Список тем",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Фильтрация задач по ID автора",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы с темами",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение страницы с темами",
                        "name": "offser",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка тем",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_themes_transport_http.ThemeDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создать новую тему в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Создать тему",
                "parameters": [
                    {
                        "description": "CreateTheme тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_themes_transport_http.CreateThemeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешно созданная тема",
                        "schema": {
                            "$ref": "#/definitions/internal_features_themes_transport_http.CreateThemeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Author not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/themes/{id}": {
            "get": {
                "description": "Получение конкретной темы в системе по ее ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Получение темы",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID получаемой темы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Тема успешно найдена",
                        "schema": {
                            "$ref": "#/definitions/internal_features_themes_transport_http.GetThemeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Theme not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаление существующей темы в системе по ее ID",
                "tags": [
                    "themes"
                ],
                "summary": "Удаление темы",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID удаляемой темы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление темы"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Theme not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Изменение информации об уже существующем в системе теме\n### Логика обновления полей (Three-state logic):\n1. **Поле не передано**: ` + "`" + `\"description\"` + "`" + ` игнорируется, значение в БД не меняется\n2. **Явно передано значение**: ` + "`" + `\"description\": \"Пойти на  тренировку\"` + "`" + ` - устанавливает новое описание в БД\n3. **Передан null**: ` + "`" + `\"description\": null` + "`" + ` - очищает поле в БД (set to NULL)\nОграничение: ` + "`" + `title` + "`" + ` и ` + "`" + `subject` + "`" + ` не может быть выставлен как null",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes"
                ],
                "summary": "Изменение темы",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID изменяемой темы",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchTheme тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_themes_transport_http.PatchThemeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное изменение темы",
                        "schema": {
                            "$ref": "#/definitions/internal_features_themes_transport_http.PatchThemeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Theme not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/themes_user": {
            "get": {
                "description": "Получение списка тем пользователя с опциональной пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes_user"
                ],
                "summary": "Список тем пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Фильтрация задач по ID автора",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Фильтрация задач по ID темы",
                        "name": "theme_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы с темами пользователя",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение страницы с темами пользователя",
                        "name": "offser",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка тем пользователя",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_domain.ThemeUser"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создать новую тему для пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes_user"
                ],
                "summary": "Создать тему для пользователя",
                "parameters": [
                    {
                        "description": "CreateThemeUser тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_theme_users_transport_http.CreateThemeUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешно созданная тема для пользователя",
                        "schema": {
                            "$ref": "#/definitions/internal_features_theme_users_transport_http.CreateThemeUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Author not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/themes_user/{id}": {
            "get": {
                "description": "Получение конкретной темы пользователя в системе по ее ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes_user"
                ],
                "summary": "Получение темы пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID получаемой темы пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Тема пользователя успешно найдена",
                        "schema": {
                            "$ref": "#/definitions/internal_features_theme_users_transport_http.GetThemeUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "ThemeUser not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаление существующей темы пользователя в системе по ее ID",
                "tags": [
                    "themes_user"
                ],
                "summary": "Удаление темы пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID удаляемой темы пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление темы пользователя"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "ThemeUser not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Изменение информации об уже существующем в системе теме пользователя\nОграничение: ` + "`" + `completed` + "`" + ` не может быть выставлен как null",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "themes_user"
                ],
                "summary": "Изменение темы пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID изменяемой темы пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchThemeUser тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_theme_users_transport_http.PatchThemeUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное изменение темы пользователя",
                        "schema": {
                            "$ref": "#/definitions/internal_features_theme_users_transport_http.PatchThemeUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "ThemeUser not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Получение списка пользователей с опциональной пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Список пользователей",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Размер страницы с пользователями",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение страницы с пользователями",
                        "name": "offser",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка пользователей",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_users_transport_http.UserDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создать нового пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "CreateUser тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешно созданный пользователь",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Получение конкретного пользователя в системе по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получение пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID получаемого пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно найден",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаление существующего пользователя в системе по его ID",
                "tags": [
                    "users"
                ],
                "summary": "Удаление пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID удаляемого пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление пользователя"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Изменение информации об уже существующем в системе пользователе\n### Логика обновления полей (Three-state logic):\n1. **Поле не передано**: ` + "`" + `\"phone_number\"` + "`" + ` игнорируется, значение в БД не меняется\n2. **Явно передано значение**: ` + "`" + `\"phone_number\": \"+71112223344\"` + "`" + ` - устанавливает новый номер телефона в БД\n3. **Передан null**: ` + "`" + `\"phone_number\": null` + "`" + ` - очищает поле в БД (set to NULL)\nОграничение: ` + "`" + `full_name` + "`" + ` не может быть выставлен как null",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Изменение пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID изменяемого пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchUser тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное изменение пользователя",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_LayMan011_Golang-My-Study_internal_core_domain.ThemeUser": {
            "type": "object",
            "properties": {
                "additionAt": {
                    "type": "string"
                },
                "completed": {
                    "type": "boolean"
                },
                "completedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "percentages": {
                    "type": "integer"
                },
                "themeID": {
                    "type": "integer"
                },
                "userID": {
                    "type": "integer"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "github_com_LayMan011_Golang-My-Study_internal_core_transport_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "full error text"
                },
                "message": {
                    "type": "string",
                    "example": "short human-readable message"
                }
            }
        },
        "github_com_LayMan011_Golang-My-Study_internal_core_transport_http_types.Nullable-bool": {
            "type": "object",
            "properties": {
                "set": {
                    "type": "boolean"
                },
                "value": {
                    "type": "boolean"
                }
            }
        },
        "internal_features_theme_users_transport_http.CreateThemeUserRequest": {
            "type": "object",
            "required": [
                "theme_id",
                "user_id"
            ],
            "properties": {
                "theme_id": {
                    "type": "integer",
                    "example": 1
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_theme_users_transport_http.CreateThemeUserResponse": {
            "type": "object",
            "properties": {
                "addition_at": {
                    "type": "string",
                    "example": "2026-02-26T10:30:00Z"
                },
                "completed": {
                    "type": "boolean",
                    "example": false
                },
                "completed_at": {
                    "type": "string",
                    "example": "null"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "percentages": {
                    "type": "integer",
                    "example": 0
                },
                "theme_id": {
                    "type": "integer",
                    "example": 3
                },
                "user_id": {
                    "type": "integer",
                    "example": 4
                },
                "version": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "internal_features_theme_users_transport_http.GetThemeUserResponse": {
            "type": "object",
            "properties": {
                "addition_at": {
                    "type": "string",
                    "example": "2026-02-26T10:30:00Z"
                },
                "completed": {
                    "type": "boolean",
                    "example": false
                },
                "completed_at": {
                    "type": "string",
                    "example": "null"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "percentages": {
                    "type": "integer",
                    "example": 0
                },
                "theme_id": {
                    "type": "integer",
                    "example": 3
                },
                "user_id": {
                    "type": "integer",
                    "example": 4
                },
                "version": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "internal_features_theme_users_transport_http.PatchThemeUserRequest": {
            "type": "object"
        },
        "internal_features_theme_users_transport_http.PatchThemeUserResponse": {
            "type": "object",
            "properties": {
                "addition_at": {
                    "type": "string",
                    "example": "2026-02-26T10:30:00Z"
                },
                "completed": {
                    "type": "boolean",
                    "example": false
                },
                "completed_at": {
                    "type": "string",
                    "example": "null"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "percentages": {
                    "type": "integer",
                    "example": 0
                },
                "theme_id": {
                    "type": "integer",
                    "example": 3
                },
                "user_id": {
                    "type": "integer",
                    "example": 4
                },
                "version": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "internal_features_themes_transport_http.CreateThemeRequest": {
            "type": "object",
            "required": [
                "author_user_id",
                "subject",
                "title"
            ],
            "properties": {
                "author_user_id": {
                    "type": "integer",
                    "example": 1
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1,
                    "example": "Подготовка к ЕГЭ по русскому языку за 3 месяца"
                },
                "subject": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1,
                    "example": "Русский язык"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Подготовка к ЕГЭ по русскому языку"
                }
            }
        },
        "internal_features_themes_transport_http.CreateThemeResponse": {
            "type": "object",
            "properties": {
                "all_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "author_user_id": {
                    "type": "integer",
                    "example": 2
                },
                "create_at": {
                    "type": "string",
                    "example": "Профильная математика"
                },
                "description": {
                    "type": "string",
                    "example": "Подготовка к ЕГЭ по профильной математике"
                },
                "id": {
                    "type": "integer",
                    "example": 13
                },
                "number_of_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "number_of_users": {
                    "type": "integer",
                    "example": 0
                },
                "price": {
                    "type": "integer",
                    "example": 50
                },
                "subject": {
                    "type": "string",
                    "example": "2026-02-26T10:30:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Математика"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_themes_transport_http.GetThemeResponse": {
            "type": "object",
            "properties": {
                "all_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "author_user_id": {
                    "type": "integer",
                    "example": 2
                },
                "create_at": {
                    "type": "string",
                    "example": "Профильная математика"
                },
                "description": {
                    "type": "string",
                    "example": "Подготовка к ЕГЭ по профильной математике"
                },
                "id": {
                    "type": "integer",
                    "example": 13
                },
                "number_of_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "number_of_users": {
                    "type": "integer",
                    "example": 0
                },
                "price": {
                    "type": "integer",
                    "example": 50
                },
                "subject": {
                    "type": "string",
                    "example": "2026-02-26T10:30:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Математика"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_themes_transport_http.PatchThemeRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Подготовка к ЕГЭ по Биологии"
                },
                "subject": {
                    "type": "string",
                    "example": "Биология"
                },
                "title": {
                    "type": "string",
                    "example": "Биология"
                }
            }
        },
        "internal_features_themes_transport_http.PatchThemeResponse": {
            "type": "object",
            "properties": {
                "all_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "author_user_id": {
                    "type": "integer",
                    "example": 2
                },
                "create_at": {
                    "type": "string",
                    "example": "Профильная математика"
                },
                "description": {
                    "type": "string",
                    "example": "Подготовка к ЕГЭ по профильной математике"
                },
                "id": {
                    "type": "integer",
                    "example": 13
                },
                "number_of_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "number_of_users": {
                    "type": "integer",
                    "example": 0
                },
                "price": {
                    "type": "integer",
                    "example": 50
                },
                "subject": {
                    "type": "string",
                    "example": "2026-02-26T10:30:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Математика"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_themes_transport_http.ThemeDTOResponse": {
            "type": "object",
            "properties": {
                "all_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "author_user_id": {
                    "type": "integer",
                    "example": 2
                },
                "create_at": {
                    "type": "string",
                    "example": "Профильная математика"
                },
                "description": {
                    "type": "string",
                    "example": "Подготовка к ЕГЭ по профильной математике"
                },
                "id": {
                    "type": "integer",
                    "example": 13
                },
                "number_of_ratings": {
                    "type": "integer",
                    "example": 0
                },
                "number_of_users": {
                    "type": "integer",
                    "example": 0
                },
                "price": {
                    "type": "integer",
                    "example": 50
                },
                "subject": {
                    "type": "string",
                    "example": "2026-02-26T10:30:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Математика"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.CreateUserRequest": {
            "type": "object",
            "required": [
                "full_name"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "Ivan Ivanov"
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10,
                    "example": "+79998887766"
                }
            }
        },
        "internal_features_users_transport_http.CreateUserResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.GetUserResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.PatchUserRequest": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Максим Максимович"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                }
            }
        },
        "internal_features_users_transport_http.PatchUserResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.UserDTOResponse": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:5050",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Golang My Project",
	Description:      "Learning Progress REST-API scheme",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
